### ISSUE TITLE
Travis-generated .deb packages fail to start

### ISSUE THREAD

**Issue by pocc** [pocc/meraki-client-vpn#49]
## Problem
* Travis-generated .deb packages fail to start
* This is on both 0.7.3 and 0.8
* Build made by hand at 0.7 works fine 
### 0.8 travis build#111 (fa8bd5e)
https://travis-ci.org/pocc/merlink/builds/400353842

### 0.7.3 travis build#103 (ecd31ca)
https://travis-ci.org/pocc/merlink/builds/399901479

### Error output when starting merlink on both 0.7.3 and 0.8
Traceback (most recent call last):
  File "merlink/merlink.py", line 11, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ModuleNotFoundError: No module named 'PyQt5.sip'
[13326] Failed to execute script merlink

## Firmware/hardware
Testing on virtual machine: Ubuntu 18.04

## Analysis
* As merlink is looking for something in the virtualenv referencing a travis directory, there's probably something hardcoded that shouldn't be

**Comment by pocc** [comment]
### Use these commands to start:
```
pip3 install --user https://github.com/pyinstaller/pyinstaller/tarball/develop
pip3 install --user -r requirements.txt
pyinstaller -y <location of pyinstaller.spec> 
```
### Use git bisect to find bug
Latest commit (broken): 386e1fff48611f0b91618c816d6207a99923f8f9
Earliest confirmed working commit: 954df0f0a20054e3b29ab887f77b3b8966334268

**Comment by pocc** [comment]
This fails on 16.04 Ubuntu if the latest build of pyinstaller is not used:
`pip3 install --user https://github.com/pyinstaller/pyinstaller/tarball/develop`

* Testing against travis ci again using latest pyinstaller
* Additional testing required on 18.04

**Comment by pocc** [comment]
# Fixed in dev. There were 3 problems here:
## Problem 1: libdrm.so.2 was not removed for deb packages
### Problem
* removal of libdrm.so.2 in fpm_build.sh came after files were copied from dist to build directory
* This had the effect that the intended removal never happened
* If libdrm.so.2 isn't found, the OS' is used instead, which doesn't cause an error
* This had been previously fixed, but moving commands around must have caused this error 
### Error output
* Merlink doesn't start when this file is not removed:
```
Traceback (most recent call last):
  File "merlink/merlink.py", line 11, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
[12251] Failed to execute script merlink
```

### Resolution
Include this line after pyinstaller has run but before we build with fpm, debreate, etc.

`rm -fv dist/merlink/libdrm.so.2` 

## Problem 2: Build and deploy targets didn't match
### Problem
* As build and deploy targets didn't match, nothing
* Secondary problem is that travis ci doesn't error when a build target is not found. There will literally just be a blank line for both deploy success AND failure (grrr)

### Resolution
Putting in debugging commands in build_nix_packages.sh because travis ci is lacking them here:
```
# The following should match EXACTLY if they are to be deployed to a github release
echo "Built targets:"
ls -1d build/* | grep merlink
echo "Deploy targets:"
echo "build/merlink-${VERSION}_x64.deb"
echo "build/merlink-${VERSION}_x64.rpm"
echo "build/merlink-${VERSION}_x64.tar.gz"
echo "build/merlink-${VERSION}_x64.dmg"
```

## Problem 3: Errors due to not using latest pyinstaller build 
### Problem
* Same as errors in this issue's description "Error output when starting merlink on both 0.7.3 and 0.8"
* Repeating here for completeness:
```
Traceback (most recent call last):
File "merlink/merlink.py", line 11, in 
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ModuleNotFoundError: No module named 'PyQt5.sip'
[13326] Failed to execute script merlink
```
### Resolution
Make sure to include dev version of pyinstaller in requirements.txt with line like so:
```
# Use PyInstaller dev version (currently 3.4dev) 
https://github.com/pyinstaller/pyinstaller/tarball/develop
```
